WITH RECURSIVE cte AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM cte
    WHERE HOUR < 23
)

SELECT 
        CTE.HOUR,
        IF(SUB_QUERY.COUNT IS NULL, 0, SUB_QUERY.COUNT) AS 'COUNT'
    FROM (
            SELECT COUNT(*) AS 'COUNT', HOUR(DATETIME) AS 'HOUR'
            FROM ANIMAL_OUTS 
            GROUP BY HOUR(DATETIME)
        ) AS SUB_QUERY
    RIGHT OUTER JOIN cte AS CTE
    ON CTE.HOUR = SUB_QUERY.HOUR
    ;